source 'https://github.com/CocoaPods/Specs.git'

target 'NSURLSession-PromiseKit', :exclusive => true do
  pod "NSURLSession-PromiseKit", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "NSURLSession-PromiseKit", :path => "../"

  
end
