source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'NSURLSession-PromiseKit_Example', :exclusive => true do
  pod "NSURLSession-PromiseKit", :path => "../"
end

target 'NSURLSession-PromiseKit_Tests', :exclusive => true do
  pod "NSURLSession-PromiseKit", :path => "../"

  pod 'Quick', '~> 0.3.1'
  pod 'Nimble'
end
