# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

use_frameworks!

target 'SwiftExample' do
    pod "NSURLSession-PromiseKit", :path => "../../"
end

target 'SwiftExampleTests' do

end

